sudo: required
services:
  - docker
before_install:
  - openssl aes-256-cbc -K $encrypted_9f3b5599b056_key -iv $encrypted_9f3b5599b056_iv -in service-account.json.enc -out service-account.json -d
  # Install Google cloud SDK CLI
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  # Apply configuration that will modify our shell inside TRAVIS
  - source $HOME/google-cloud-sdk/path.bash.inc
  # Install kubectl command
  - gcloud components update kubectl
  # Authenticate service account with the key file service-account.json
  - gcloud auth activate-service-account --key-file service-account.json